### ISSUE TITLE
Docker Env Variables Ignored

### ISSUE THREAD

**Issue by Ryonez** [xthursdayx/ferdi-server-docker#1]
The logs show that they are seen, but the .env file and the config file seem to outright ignore them.

Log:
![image](https://user-images.githubusercontent.com/16157130/65811694-7ca43080-e210-11e9-9d2d-073433f89c15.png)

.env File:
![image](https://user-images.githubusercontent.com/16157130/65811697-95ace180-e210-11e9-8723-b119982eb2be.png)

Config File:
![image](https://user-images.githubusercontent.com/16157130/65811705-acebcf00-e210-11e9-8784-801957557bf0.png)

unRAID is the OS, using the docker template for this from CA.

**Comment by xthursdayx** [comment]
Hmmm, I'll check on this and report back. I've just been using the internal SQLite database, so hadn't run into this problem. Are all the variables that appear in the log being set by dockerMan via the `docker run` in unRAID?

**Comment by Ryonez** [comment]
They are.

**Comment by xthursdayx** [comment]
@Ryonez apologies for the delay. I think that I was able to fix this with the commit. Please delete your image and ferdi-server config folder and reinstall with the new image and the new ferdi-server unRAID template I uploaded here: https://github.com/xthursdayx/docker-templates/blob/master/ferdi-server.xml

The new template should be updated on Community Apps, but I'm not sure how quickly that happens. 

Please report back if you have any more issues. Cheers.
